### ISSUE TITLE
Quoted numbers in yaml sometimes cause an error

### ISSUE THREAD

**Issue by mrog** [iph/noctilucent#178]
There's inconsistent handling of quoted numbers in yaml CloudFormation templates.  Consider this example:
```
AWSTemplateFormatVersion: 2010-09-09
Parameters:
  Param1:
    Type: Number
    Default: !!int "0"  # This line does not cause an error.
Conditions:
  Condition1:
    "Fn::Equals":
    - "Fn::Select":
      - !!int "0"  # This line causes an error unless you remove the quotes around the zero.
      - "Fn::Split":
        - "delimiter"
        - "string"
    - ""
Resources:
```

The first instance of `!!int "0"` is accepted by noctilucent, but the second instance causes this error:
```
Error: Conditions.Condition1.Fn::Equals[0].Fn::Select[0]: invalid type: string "0", expected usize at line 10 column 9
```
